check_sign: true
mysql:
  connect_time_out: 10
  charset: utf8
  main:
    database: redeast_main
    dns: 10.11.1.90
    port: 3306
    username: root
    password: 123456
  admin:
    database: redeast_admin
    dns: 10.11.1.90
    port: 3306
    username: root
    password: 123456
logging:
  file_path: /var/www/html/log/go #日志记录在哪个文件
  file_write: false   #是否写入日志中
  file_max_age: 168   #保存多少个小时
  file_rotation_time: 24   #多少小时做切割
sign:
  check: true
  expire: 300
  keys:
    web: 12112321  #前端传Web，因为被解析成结构体Web
    ios: 14e2413   #前端传IOS
    android: 4525434  #前端传Android

msg:
  account: 639581001530687959952067
  secret: B9907AFA504D77FB4C9C3448C2661BB2